### ISSUE TITLE
Errors After Recent Flutter Updates

### ISSUE THREAD

**Issue by Cwiesen** [SteveAlexander/route_kit#1]
A number of errors have arisen after a recent flutter upgrade, rendering this package unusable. Would it be possible to update the code to fix these errors?

**Comment by SteveAlexander** [comment]
There are no analysis errors. Can you describe the errors you're seeing?

**Comment by Cwiesen** [comment]
I'm getting 3 errors for route_kit:
 - In adapter.dart, I'm getting `Missing concrete implementation of 'RouterDelegate.setRestoredRoutePath'.
Try implementing the missing method, or make the class abstract.`
 - In  app_router.dart, I'm getting `'DelegatedRouteInformationProvider.value' ('RouteInformation? Function()') isn't a valid override of 'ValueListenable.value' ('RouteInformation Function()').`
 - In inactive_routing_information_provider.dart, I'm getting `'InactiveRouteInformationProvider.value' ('RouteInformation? Function()') isn't a valid override of 'ValueListenable.value' ('RouteInformation Function()').`
 
 I ran into issues when trying to build DawnMountain, which has route_kit as a dependency.

**Comment by SteveAlexander** [comment]
Try using the “clone repo” url in your pubspec.yaml

https://github.com/SteveAlexander/route_kit

(Go to that page and look up the clone repo url)

Also, please add the output of flutter doctor

**Comment by Cwiesen** [comment]
I'm having the same issues when using the clone repo for the dependency. 
Here's my flutter doctor output:
`[✓] Flutter (Channel master, 2.3.0-17.0.pre.352, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.352 at /Users/cwiesen/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f4f1c2103e (20 hours ago), 2021-06-14 20:34:02 +0200
    • Engine revision e1d2d4b264
    • Dart version 2.14.0 (build 2.14.0-210.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cwiesen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.2
    • Dart plugin version 202.8346

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • 1319CA2A-7A74-4344-826E-E39EA2895930 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      91.0.4472.101

• No issues found!
`

**Comment by SteveAlexander** [comment]
Ok, you're on Flutter master. Move to Flutter beta or Flutter stable and there will not be the problems.

There's no guarantee these changes will be present on beta later on — they might or might not be.

**Comment by Cwiesen** [comment]
That did it, thanks Steve!
